"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "../../lib/AntdRegistry";
import { ConfigProvider } from "antd";
import theme from "@/theme/themeConfig";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Delphicom",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <StyledComponentsRegistry>
          <ConfigProvider theme={theme}>
            <SessionProvider>{children}</SessionProvider>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
